title: Pramod Kotipalli
subtitle: Masters candidate, Stanford CS

# Site configurations
timezone: UTC
permalink: "/posts/:year/:month/:title/"
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed
repository: p13i/p13i.github.io
include:
- static

# Dependencies
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-github-metadata
- jekyll-seo-tag
