---
title: Pramod Kotipalli
timezone: UTC
subtitle: 
permalink: "/posts/:year/:month/:title/"
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-github-metadata
- jekyll-seo-tag
- jekyll-paginate
include:
- static
- js
future: true
paginate: 5
paginate_path: "/posts/page/:num/"
sass:
  sass_dir: "./_sass"
  style: :compressed
repository: p13i/p13i.github.io